### PR TITLE
adding strangelove saga-testnet gentx

### PR DESCRIPTION
**Pull request by danbryan**

### CODE REVIEW

**Comment by lukitsbrian** [comment]
@danbryan your signature seems to be invalid, please make sure you are using the correct account number and chain id.

**Comment by danbryan** [comment]
@lukitsbrian any idea what  i did wrong.  Here is the command i did.

list keys
```
sscd keys list                    
[{"name":"strangelove","type":"local","address":"saga1qp5vg3yj54ppgwtrs9xv7qzt97xegc88p0fxz9","pubkey":"{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A3v4+yW0qYNb7eg24gWd+MeDXIJVv2ZRhu7QaNna7gyQ\"}"}]%

```
Then get the account number
```
jq -r '.app_state.auth.accounts[] | select( .address == "saga1qp5vg3yj54ppgwtrs9xv7qzt97xegc88p0fxz9")' genesis.json
{
  "@type": "/cosmos.auth.v1beta1.BaseAccount",
  "address": "saga1qp5vg3yj54ppgwtrs9xv7qzt97xegc88p0fxz9",
  "pub_key": null,
  "account_number": "9",
  "sequence": "0"
}
```
Then create the gentx
```
sscd gentx strangelove 8000000utsaga \
    --chain-id ssc-testnet-1 \
    --account-number 9 \
    --ip 38.109.200.36 \
    --p2p-port 44440
````

**Comment by danbryan** [comment]
@lukitsbrian mind trying again?

**Comment by lukitsbrian** [comment]
@danbryan looks good!

**Review by lukitsbrian — APPROVED** [review]

**Pull request merged**
